<?php 
namespace Neos\SwiftMailer\Transport;

/*
 * This file is part of the Neos.SwiftMailer package.
 *
 * (c) Contributors of the Neos Project - www.neos.io
 *
 * This package is Open Source Software. For the full copyright and license
 * information, please view the LICENSE file which was distributed with this
 * source code.
 */

use Neos\Flow\Annotations as Flow;
use Neos\SwiftMailer\TransportInterface;

/**
 * A logging swift transport for functional tests and development. It stores and logs sent messages.
 */
class LoggingTransport_Original implements TransportInterface
{

    /**
     * Store sent messages for testing
     *
     * @var array
     */
    static protected $deliveredMessages = array();

    /**
     * @Flow\Inject
     * @var \Neos\Flow\Log\SystemLoggerInterface
     */
    protected $systemLogger;

    /**
     * The logging transport is always started
     *
     * @return boolean Always TRUE for this transport
     */
    public function isStarted()
    {
        return true;
    }

    /**
     * No op
     *
     * @return void
     */
    public function start()
    {
    }

    /**
     * No op
     *
     * @return void
     */
    public function stop()
    {
    }

    /**
     * "Send" the given Message. This transport will add it to a stored collection of sent messages
     * for testing purposes and log the message to the system logger.
     *
     * @param \Swift_Mime_Message $message The message to send
     * @param array &$failedRecipients Failed recipients
     * @return integer
     */
    public function send(\Swift_Mime_Message $message, &$failedRecipients = null)
    {
        self::$deliveredMessages[] = $message;

        $this->systemLogger->log('Sent email to ' . $this->buildStringFromEmailAndNameArray($message->getTo()), LOG_DEBUG, array(
            'message' => $message->toString()
        ));

        return count((array)$message->getTo()) + count((array)$message->getCc()) + count((array)$message->getBcc());
    }

    /**
     * Builds a plaintext-compatible string representing an array of given E-Mail addresses.
     *
     * @param array $addresses The addresses where the key is the email address and the value is a name
     * @return string Looking like "John Doe <demo@example.org>, Jeanne Dough <foo@example.org>, somebody@example.org"
     */
    protected function buildStringFromEmailAndNameArray(array $addresses)
    {
        $results = array();
        foreach ($addresses as $emailAddress => $name) {
            if (strlen($name) > 0) {
                $results[] = sprintf('%s <%s>', $name, $emailAddress);
            } else {
                $results[] = $emailAddress;
            }
        }
        return implode(', ', $results);
    }

    /**
     * No op
     *
     * @param \Swift_Events_EventListener $plugin
     * @return void
     */
    public function registerPlugin(\Swift_Events_EventListener $plugin)
    {
    }

    /**
     * Get delivered messages that were sent through this transport
     *
     * @return array
     */
    static public function getDeliveredMessages()
    {
        return self::$deliveredMessages;
    }

    /**
     * Reset the delivered messages (e.g. for tearDown in functional test)
     *
     * @return void
     */
    static public function reset()
    {
        self::$deliveredMessages = array();
    }

}

#
# Start of Flow generated Proxy code
#
namespace Neos\SwiftMailer\Transport;

use Doctrine\ORM\Mapping as ORM;
use Neos\Flow\Annotations as Flow;

/**
 * A logging swift transport for functional tests and development. It stores and logs sent messages.
 */
class LoggingTransport extends LoggingTransport_Original implements \Neos\Flow\ObjectManagement\Proxy\ProxyInterface {

    use \Neos\Flow\ObjectManagement\Proxy\ObjectSerializationTrait, \Neos\Flow\ObjectManagement\DependencyInjection\PropertyInjectionTrait;


    /**
     * Autogenerated Proxy Method
     */
    public function __construct()
    {
        if ('Neos\SwiftMailer\Transport\LoggingTransport' === get_class($this)) {
            $this->Flow_Proxy_injectProperties();
        }
    }

    /**
     * Autogenerated Proxy Method
     */
    public function __sleep()
    {
            $result = NULL;
        $this->Flow_Object_PropertiesToSerialize = array();

        $transientProperties = array (
);
        $propertyVarTags = array (
  'deliveredMessages' => 'array',
  'systemLogger' => '\\Neos\\Flow\\Log\\SystemLoggerInterface',
);
        $result = $this->Flow_serializeRelatedEntities($transientProperties, $propertyVarTags);
        return $result;
    }

    /**
     * Autogenerated Proxy Method
     */
    public function __wakeup()
    {

        $this->Flow_setRelatedEntities();
        $this->Flow_Proxy_injectProperties();
    }

    /**
     * Autogenerated Proxy Method
     */
    private function Flow_Proxy_injectProperties()
    {
        $this->Flow_Proxy_LazyPropertyInjection('Neos\Flow\Log\SystemLoggerInterface', 'Neos\Flow\Log\Logger', 'systemLogger', '717e9de4d0309f4f47c821b9257eb5c2', function() { return \Neos\Flow\Core\Bootstrap::$staticObjectManager->get('Neos\Flow\Log\SystemLoggerInterface'); });
        $this->Flow_Injected_Properties = array (
  0 => 'systemLogger',
);
    }
}
# PathAndFilename: /var/www/php/Packages/Application/Neos.SwiftMailer/Classes/Transport/LoggingTransport.php
#