<?php

namespace PackageVersions;

/**
 * This class is generated by ocramius/package-versions, specifically by
 * @see \PackageVersions\Installer
 *
 * This file is overwritten at every run of `composer install` or `composer update`.
 */
final class Versions
{
    const VERSIONS = array (
  'doctrine/annotations' => 'v1.4.0@54cacc9b81758b14e3ce750f205a393d52339e97',
  'doctrine/cache' => 'v1.6.1@b6f544a20f4807e81f7044d31e679ccbb1866dc3',
  'doctrine/collections' => 'v1.4.0@1a4fb7e902202c33cce8c55989b945612943c2ba',
  'doctrine/common' => 'v2.7.2@930297026c8009a567ac051fd545bf6124150347',
  'doctrine/dbal' => 'v2.5.12@7b9e911f9d8b30d43b96853dab26898c710d8f44',
  'doctrine/inflector' => 'v1.1.0@90b2128806bfde671b6952ab8bea493942c1fdae',
  'doctrine/instantiator' => '1.0.5@8e884e78f9f0eb1329e445619e04456e64d8051d',
  'doctrine/lexer' => 'v1.0.1@83893c552fd2045dd78aef794c31e694c37c0b8c',
  'doctrine/migrations' => 'v1.3.1@fda27fc96d20a1abd46d4526387c7d6d416da263',
  'doctrine/orm' => 'v2.5.6@e6c434196c8ef058239aaa0724b4aadb0107940b',
  'neos/cache' => '4.0.6@291c378cd9bde440778f0b04ba361a2a76ff6efe',
  'neos/composer-plugin' => '2.0.1@cd20e3c9b548127f4fa1e0f31662072bf82250d4',
  'neos/eel' => '4.0.6@acc9c3dc40e85ee59e8012f7763ae99f320fa95e',
  'neos/error-messages' => '4.0.6@246d04e372923e94255d08c92226c2d438292ad3',
  'neos/flow' => '4.0.6@e5b357bcb3e8f86724dbda057f562b44a60abe2a',
  'neos/fluid-adaptor' => '4.0.6@5c101d3185b577c35b073e6042e33eb35211215a',
  'neos/swiftmailer' => '6.0.0@df3fc7c6914c174ff50cd79f90f050394c3cebf6',
  'neos/utility-arrays' => '4.0.6@754cf6d4eb25960c152b38058fe07a1565fcf594',
  'neos/utility-files' => '4.0.6@0b7e0c5905dfc631276475226eec1119cdc0ceac',
  'neos/utility-lock' => '4.0.6@39d02c1d71ef09d4ba7e67a4eb832989f4202fbb',
  'neos/utility-mediatypes' => '4.0.6@34689284769858be7840eb3eff5a3216982a02b4',
  'neos/utility-objecthandling' => '4.0.6@cd58c51647b03153a31cb760b4a2c56660c91218',
  'neos/utility-opcodecache' => '4.0.6@60e15ac15afda229149ed05786ec5576f081cc4f',
  'neos/utility-pdo' => '4.0.6@66fd754c1a1e514448856a267c2074d0a6dc829f',
  'neos/utility-schema' => '4.0.6@5fc2689ad17d70480bf6682ef1ef0c96f133d3cb',
  'neos/utility-unicode' => '4.0.6@28ad5725c93198f7e18cb075b38fefc00434cce2',
  'neos/welcome' => '4.0.0@d7dfac9abc7e75d952e4299af1f7bbfc44e2704b',
  'ocramius/package-versions' => '1.1.2@51e867c70f0799790b3e82276875414ce13daaca',
  'ocramius/proxy-manager' => '2.0.4@a55d08229f4f614bf335759ed0cf63378feeb2e6',
  'paragonie/random_compat' => 'v2.0.10@634bae8e911eefa89c1abfbf1b66da679ac8f54d',
  'pelago/emogrifier' => 'V1.2.0@a1db453bb504597d821efcc04b21c79a6021e00c',
  'psr/log' => '1.0.2@4ebe3a8bf773a19edfe0a84b6585ba3d401b724d',
  'ramsey/uuid' => '3.6.1@4ae32dd9ab8860a4bbd750ad269cba7f06f7934e',
  'sandstorm/templatemailer' => '1.1.0@68599006ecd2fa2b1114273fe66168b3867740ce',
  'sandstorm/usermanagement' => '5.0.4@3dc8f791bce89e19da38c270c612c2e9b92d0620',
  'swiftmailer/swiftmailer' => 'v5.4.8@9a06dc570a0367850280eefd3f1dc2da45aef517',
  'symfony/console' => 'v2.8.19@86407ff20855a5eaa2a7219bd815e9c40a88633e',
  'symfony/debug' => 'v3.0.9@697c527acd9ea1b2d3efac34d9806bf255278b0a',
  'symfony/dom-crawler' => 'v2.8.19@24b1a3ffa5b64e4f8b1c5f2cdffd16368640704a',
  'symfony/polyfill-mbstring' => 'v1.3.0@e79d363049d1c2128f133a2667e4f4190904f7f4',
  'symfony/yaml' => 'v2.8.19@286d84891690b0e2515874717e49360d1c98a703',
  'typo3fluid/fluid' => '2.1.3@52ccc0a1d4f1039b95a289dc44b2f6885a463799',
  'zendframework/zend-code' => '3.1.0@2899c17f83a7207f2d7f53ec2f421204d3beea27',
  'zendframework/zend-eventmanager' => '3.1.0@c3bce7b7d47c54040b9ae51bc55491c72513b75d',
  'mikey179/vfsStream' => 'v1.6.4@0247f57b2245e8ad2e689d7cee754b45fbabd592',
  'myclabs/deep-copy' => '1.6.1@8e6e04167378abf1ddb4d3522d8755c5fd90d102',
  'neos/behat' => 'dev-master@1be9fcc6ab631ad4c6e4eed9d22919aafc33ebe3',
  'neos/buildessentials' => '4.0.0@e5d3108793c8a457283f1820d2d32457bd7800ff',
  'neos/kickstarter' => '4.0.6@b6ff51028b4a76e32ae234748192bf8b1058c392',
  'phpdocumentor/reflection-common' => '1.0@144c307535e82c8fdcaacbcfc1d6d8eeb896687c',
  'phpdocumentor/reflection-docblock' => '3.1.1@8331b5efe816ae05461b7ca1e721c01b46bafb3e',
  'phpdocumentor/type-resolver' => '0.2.1@e224fb2ea2fba6d3ad6fdaef91cd09a172155ccb',
  'phpspec/prophecy' => 'v1.7.0@93d39f1f7f9326d746203c7c056f300f7f126073',
  'phpunit/php-code-coverage' => '4.0.8@ef7b2f56815df854e66ceaee8ebe9393ae36a40d',
  'phpunit/php-file-iterator' => '1.4.2@3cc8f69b3028d0f96a9078e6295d86e9bf019be5',
  'phpunit/php-text-template' => '1.2.1@31f8b717e51d9a2afca6c9f046f5d69fc27c8686',
  'phpunit/php-timer' => '1.0.9@3dcf38ca72b158baf0bc245e9184d3fdffa9c46f',
  'phpunit/php-token-stream' => '1.4.11@e03f8f67534427a787e21a385a67ec3ca6978ea7',
  'phpunit/phpunit' => '5.4.8@3132365e1430c091f208e120b8845d39c25f20e6',
  'phpunit/phpunit-mock-objects' => '3.4.3@3ab72b65b39b491e0c011e2e09bb2206c2aa8e24',
  'sebastian/code-unit-reverse-lookup' => '1.0.1@4419fcdb5eabb9caa61a27c7a1db532a6b55dd18',
  'sebastian/comparator' => '1.2.4@2b7424b55f5047b47ac6e5ccb20b2aea4011d9be',
  'sebastian/diff' => '1.4.1@13edfd8706462032c2f52b4b862974dd46b71c9e',
  'sebastian/environment' => '2.0.0@5795ffe5dc5b02460c3e34222fee8cbe245d8fac',
  'sebastian/exporter' => '1.2.2@42c4c2eec485ee3e159ec9884f95b431287edde4',
  'sebastian/global-state' => '1.1.1@bc37d50fea7d017d3d340f230811c9f1d7280af4',
  'sebastian/object-enumerator' => '1.0.0@d4ca2fb70344987502567bc50081c03e6192fb26',
  'sebastian/recursion-context' => '1.0.5@b19cc3298482a335a95f3016d2f8a6950f0fbcd7',
  'sebastian/resource-operations' => '1.0.0@ce990bb21759f94aeafd30209e8cfcdfa8bc3f52',
  'sebastian/version' => '2.0.1@99732be0ddb3361e16ad77b68ba41efc8e979019',
  'webmozart/assert' => '1.2.0@2db61e59ff05fe5126d152bd0655c9ea113e550f',
  'neos/flow-base-distribution' => '1.0.0.0@',
);

    private function __construct()
    {
    }

    /**
     * @throws \OutOfBoundsException if a version cannot be located
     */
    public static function getVersion(string $packageName) : string
    {
        if (! isset(self::VERSIONS[$packageName])) {
            throw new \OutOfBoundsException(
                'Required package "' . $packageName . '" is not installed: cannot detect its version'
            );
        }

        return self::VERSIONS[$packageName];
    }
}
