<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname(dirname($vendorDir));

return array(
    'phpDocumentor\\Reflection\\' => array($vendorDir . '/phpdocumentor/reflection-common/src', $vendorDir . '/phpdocumentor/type-resolver/src', $vendorDir . '/phpdocumentor/reflection-docblock/src'),
    'Zend\\EventManager\\' => array($vendorDir . '/zendframework/zend-eventmanager/src'),
    'Zend\\Code\\' => array($vendorDir . '/zendframework/zend-code/src'),
    'Webmozart\\Assert\\' => array($vendorDir . '/webmozart/assert/src'),
    'TYPO3Fluid\\Fluid\\' => array($vendorDir . '/typo3fluid/fluid/src'),
    'Symfony\\Polyfill\\Mbstring\\' => array($vendorDir . '/symfony/polyfill-mbstring'),
    'Symfony\\Component\\Yaml\\' => array($vendorDir . '/symfony/yaml'),
    'Symfony\\Component\\DomCrawler\\' => array($vendorDir . '/symfony/dom-crawler'),
    'Symfony\\Component\\Debug\\' => array($vendorDir . '/symfony/debug'),
    'Symfony\\Component\\Console\\' => array($vendorDir . '/symfony/console'),
    'Sandstorm\\UserManagement\\' => array($baseDir . '/Packages/Application/Sandstorm.UserManagement/Classes'),
    'Sandstorm\\TemplateMailer\\' => array($baseDir . '/Packages/Application/Sandstorm.TemplateMailer/Classes'),
    'Ramsey\\Uuid\\' => array($vendorDir . '/ramsey/uuid/src'),
    'Psr\\Log\\' => array($vendorDir . '/psr/log/Psr/Log'),
    'Pelago\\' => array($vendorDir . '/pelago/emogrifier/Classes'),
    'PackageVersions\\' => array($vendorDir . '/ocramius/package-versions/src/PackageVersions'),
    'Neos\\Welcome\\' => array($baseDir . '/Packages/Application/Neos.Welcome/Classes'),
    'Neos\\Utility\\Unicode\\' => array($vendorDir . '/neos/utility-unicode/Classes'),
    'Neos\\Utility\\Lock\\' => array($vendorDir . '/neos/utility-lock/Classes'),
    'Neos\\Utility\\' => array($vendorDir . '/neos/utility-objecthandling/Classes', $vendorDir . '/neos/utility-arrays/Classes', $vendorDir . '/neos/utility-schema/Classes', $vendorDir . '/neos/utility-pdo/Classes', $vendorDir . '/neos/utility-opcodecache/Classes', $vendorDir . '/neos/utility-mediatypes/Classes', $vendorDir . '/neos/utility-files/Classes'),
    'Neos\\SwiftMailer\\' => array($baseDir . '/Packages/Application/Neos.SwiftMailer/Classes'),
    'Neos\\Kickstarter\\' => array($baseDir . '/Packages/Framework/Neos.Kickstarter/Classes'),
    'Neos\\FluidAdaptor\\' => array($baseDir . '/Packages/Framework/Neos.FluidAdaptor/Classes'),
    'Neos\\Flow\\Core\\Migrations\\' => array($baseDir . '/Packages/Framework/Neos.Flow/Scripts/Migrations'),
    'Neos\\Flow\\' => array($baseDir . '/Packages/Framework/Neos.Flow/Classes'),
    'Neos\\Error\\Messages\\' => array($vendorDir . '/neos/error-messages/Classes'),
    'Neos\\Eel\\' => array($baseDir . '/Packages/Framework/Neos.Eel/Classes'),
    'Neos\\ComposerPlugin\\' => array($vendorDir . '/neos/composer-plugin/Classes'),
    'Neos\\Cache\\' => array($vendorDir . '/neos/cache/Classes'),
    'Neos\\Behat\\' => array($baseDir . '/Packages/Application/Neos.Behat/Classes'),
    'Doctrine\\Instantiator\\' => array($vendorDir . '/doctrine/instantiator/src/Doctrine/Instantiator'),
    'Doctrine\\DBAL\\Migrations\\' => array($vendorDir . '/doctrine/migrations/lib/Doctrine/DBAL/Migrations'),
    'Doctrine\\Common\\Cache\\' => array($vendorDir . '/doctrine/cache/lib/Doctrine/Common/Cache'),
    'Doctrine\\Common\\Annotations\\' => array($vendorDir . '/doctrine/annotations/lib/Doctrine/Common/Annotations'),
    'Doctrine\\Common\\' => array($vendorDir . '/doctrine/common/lib/Doctrine/Common'),
    'DeepCopy\\' => array($vendorDir . '/myclabs/deep-copy/src/DeepCopy'),
);
